#!/usr/bin/env python3
"""
Generate a test APKG deck for AnkiEInk on-device testing.

Builds an Anki 2.1 collection (collection.anki2) with a mix of card states so
every Phase-1 flow can be exercised right after import:

  - 8 new cards (type 0)      -> new-card / learning flow
  - 3 learning cards (type 1) -> imported due=now, review flow immediately
  - 2 review cards (type 2)   -> due tomorrow (ivl=1), seed for next-day reviews
  - 1 small BMP referenced via <img src="dot.bmp"> to exercise media extraction

Usage:
    python generate_test_apkg.py [output_dir]
    Default output_dir: ./build/test_apkg/

Copy the resulting .apkg to the SD card at /AnkiEInk/apkg/ (or the SD root),
then use DeckList -> Import to load it.
"""

import json
import os
import sqlite3
import struct
import sys
import time
import uuid
import zipfile

DECK_NAME = "English Core"
NEW_COUNT = 8
LEARNING_COUNT = 3
REVIEW_COUNT = 2

BMP_FILENAME = "dot.bmp"


def make_bmp(path):
    """16x16 24-bit BMP: black border, white fill, black 4x4 center dot."""
    w = h = 16
    row_bytes = (w * 3 + 3) // 4 * 4
    pixel_offset = 14 + 40
    file_size = pixel_offset + row_bytes * h
    with open(path, "wb") as f:
        f.write(b"BM")
        f.write(struct.pack("<I", file_size))
        f.write(struct.pack("<HH", 0, 0))
        f.write(struct.pack("<I", pixel_offset))
        f.write(struct.pack("<I", 40))
        f.write(struct.pack("<i", w))
        f.write(struct.pack("<i", -h))  # top-down rows
        f.write(struct.pack("<HH", 1, 24))
        f.write(struct.pack("<I", 0))  # BI_RGB
        f.write(struct.pack("<I", 0))
        f.write(struct.pack("<i", 0))
        f.write(struct.pack("<i", 0))
        f.write(struct.pack("<I", 0))
        f.write(struct.pack("<I", 0))
        for y in range(h):
            row = bytearray(row_bytes)
            for x in range(w):
                on_border = x < 2 or x >= 14 or y < 2 or y >= 14
                center_dot = 6 <= x < 10 and 6 <= y < 10
                gray = 0 if (on_border or center_dot) else 255
                off = x * 3
                row[off] = gray  # B
                row[off + 1] = gray  # G
                row[off + 2] = gray  # R
            f.write(row)


def build_collection(db_path, now):
    """Create an Anki 2.1 (schema v11) collection.anki2."""
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    cur.executescript(
        """
        CREATE TABLE col (
          id integer primary key, crt integer not null, mod integer not null,
          scm integer not null, ver integer not null, dty integer not null,
          usn integer not null, ls integer not null, conf text not null,
          models text not null, decks text not null, dconf text not null,
          tags text not null);
        CREATE TABLE notes (
          id integer primary key, guid text not null, mid integer not null,
          mod integer not null, usn integer not null, tags text not null,
          flds text not null, sfld text not null, csum integer not null,
          flags integer not null, data text not null);
        CREATE TABLE cards (
          id integer primary key, nid integer not null, did integer not null,
          ord integer not null, mod integer not null, usn integer not null,
          type integer not null, queue integer not null, due integer not null,
          ivl integer not null, factor integer not null, reps integer not null,
          lapses integer not null, left integer not null, odue integer not null,
          odid integer not null, flags integer not null, data text not null);
        CREATE TABLE revlog (
          id integer primary key, cid integer not null, usn integer not null,
          ease integer not null, ivl integer not null, lastIvl integer not null,
          factor integer not null, time integer not null, type integer not null);
        CREATE INDEX ix_notes_usn ON notes (usn);
        CREATE INDEX ix_cards_usn ON cards (usn);
        CREATE INDEX ix_cards_nid ON cards (nid);
        CREATE INDEX ix_cards_sched ON cards (did, queue, due);
        CREATE INDEX ix_revlog_usn ON revlog (usn);
        CREATE INDEX ix_revlog_cid ON revlog (cid);
        """
    )

    # Minimal but valid col row: ver=11 is the Anki 2.1.x schema version.
    decks = {
        "1": {
            "id": 1,
            "name": DECK_NAME,
            "mod": now,
            "usn": 0,
            "lrnToday": [0, 0],
            "revToday": [0, 0],
            "newToday": [0, 0],
            "timeToday": [0, 0],
            "collapsed": False,
            "browserCollapsed": False,
            "desc": "Test deck generated by scripts/generate_test_apkg.py",
            "dyn": 0,
            "conf": 1,
            "extendNew": 0,
            "extendRev": 0,
            "separate": True,
        }
    }
    models = {
        "1": {
            "id": 1,
            "name": "Basic",
            "type": 0,
            "mod": now,
            "usn": 0,
            "sortf": 0,
            "did": 1,
            "tmpls": [{"name": "Card 1", "ord": 0, "qfmt": "{{Front}}", "afmt": "{{FrontSide}}<hr id=answer>{{Back}}"}],
            "flds": [
                {"name": "Front", "ord": 0, "sticky": False, "rtl": False, "font": "Arial", "size": 20},
                {"name": "Back", "ord": 1, "sticky": False, "rtl": False, "font": "Arial", "size": 20},
            ],
            "css": ".card { font-family: Arial; }",
            "latexPre": "\\documentclass[12pt]{article}",
            "latexPost": "\\begin{document}\\end{document}",
            "latexsvg": False,
            "req": [[0, "any", [0]], [1, "any", [1]]],
        }
    }
    conf = {"1": {"id": 1, "name": "Default", "mod": now, "usn": 0, "maxTaken": 60, "autoplay": True, "timer": 0,
                  "replayq": True, "new": {"bury": False, "delays": [1, 10], "initialFactor": 2500, "ints": [1, 4, 0],
                                           "order": 1, "perDay": 20}, "rev": {"bury": False, "ease4": 1.3, "ivlFct": 1,
                                           "maxIvl": 365, "perDay": 200, "hardFactor": 1.2, "fuzz": 0.05,
                                           "minSpace": 1}, "lapse": {"delays": [10], "mult": 0, "minInt": 1,
                                           "leechFails": 8, "leechAction": 0}, "dyn": False, "newMix": 0,
                  "newPerDay": 20, "revPerDay": 200, "newSortOrder": 0, "newGatherPriority": 0,
                  "newSortPriority": 0}}
    dconf = {"1": {"id": 1, "name": "Default", "mod": now, "usn": 0, "newGatherPriority": 0,
                   "newSortOrder": 0, "newSortPriority": 0, "revGatherPriority": 0, "revSortOrder": 0,
                   "revSortPriority": 0, "newPerDay": 20, "revPerDay": 200, "maxTaken": 60,
                   "bury": False, "dyn": False, "separate": True}}
    tags = {}

    cur.execute(
        "INSERT INTO col (id, crt, mod, scm, ver, dty, usn, ls, conf, models, decks, dconf, tags) "
        "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (1, now, now, now, 11, 0, 0, now, json.dumps(conf), json.dumps(models), json.dumps(decks),
         json.dumps(dconf), json.dumps(tags)),
    )

    # Word list drives the note content. A couple of notes carry HTML + an image
    # to exercise the HtmlToEpd renderer and media extraction.
    words = [
        ("apple", "苹果", "<b>apple</b>", "苹果 / 水果"),
        ("book", "书", "book", "书 / 阅读"),
        ("water", "水", "water", "水 / 液体"),
        ("mountain", "山", "mountain", "山 / 地形"),
        ("river", "河", "river", "河 / 水流"),
        ("star", "星", "star", "星 / 天体"),
        ("moon", "月亮", "moon", "月亮 / 卫星"),
        ("tree", "树", "tree", "树 / 植物"),
        ("What shape is this?", "A black dot", "What shape is this?",
         "<img src=\"%s\"> It is a black dot." % BMP_FILENAME),
        ("cloud", "云", "cloud", "云 / 天气"),
        ("fire", "火", "fire", "火 / 燃烧"),
        ("earth", "地球", "earth", "地球 / 行星"),
        ("wind", "风", "wind", "风 / 气流"),
    ]
    assert len(words) == NEW_COUNT + LEARNING_COUNT + REVIEW_COUNT

    # The importer maps Anki state onto FSRS states, so learning cards get
    # due=now (immediate reviews) and review cards land tomorrow.
    today_days = now // 86400
    note_ids = []
    for front, back, front_html, back_html in words:
        nid = int(time.time() * 1000) + len(note_ids)  # unique-ish ms ids
        note_ids.append(nid)
        guid = uuid.uuid4().hex
        flds = front_html + "\x1f" + back_html
        cur.execute(
            "INSERT INTO notes (id, guid, mid, mod, usn, tags, flds, sfld, csum, flags, data) "
            "VALUES (?,?,?,?,?,?,?,?,?,?,?)",
            (nid, guid, 1, now, 0, " test ", flds, front, 0, 0, ""),
        )

    card_id = int(time.time() * 1000) + 1000
    new_ids, learning_ids, review_ids = [], [], []

    for i in range(NEW_COUNT):
        cid = card_id + i
        new_ids.append(cid)
        cur.execute(
            "INSERT INTO cards (id, nid, did, ord, mod, usn, type, queue, due, ivl, factor, reps, "
            "lapses, left, odue, odid, flags, data) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (cid, note_ids[i], 1, 0, now, 0, 0, 0, i + 1, 0, 2500, 0, 0, 0, 0, 0, 0, ""),
        )

    for i in range(LEARNING_COUNT):
        cid = card_id + NEW_COUNT + i
        learning_ids.append(cid)
        # ivl is negative seconds in Anki; the importer maps type 1 to
        # FSRS Learning with due=now, so these are reviewable immediately.
        cur.execute(
            "INSERT INTO cards (id, nid, did, ord, mod, usn, type, queue, due, ivl, factor, reps, "
            "lapses, left, odue, odid, flags, data) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (cid, note_ids[NEW_COUNT + i], 1, 0, now, 0, 1, 1, now, -60, 2500, 1, 0, 1001, 0, 0, 0, ""),
        )

    for i in range(REVIEW_COUNT):
        cid = card_id + NEW_COUNT + LEARNING_COUNT + i
        review_ids.append(cid)
        cur.execute(
            "INSERT INTO cards (id, nid, did, ord, mod, usn, type, queue, due, ivl, factor, reps, "
            "lapses, left, odue, odid, flags, data) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (cid, note_ids[NEW_COUNT + LEARNING_COUNT + i], 1, 0, now, 0, 2, 2, today_days, 1, 2500,
             2, 0, 0, 0, 0, 0, ""),
        )
        cur.execute(
            "INSERT INTO revlog (id, cid, usn, ease, ivl, lastIvl, factor, time, type) "
            "VALUES (?,?,?,?,?,?,?,?,?)",
            (cid + 1, cid, 0, 3, 1, 0, 2500, 1000, 0),
        )

    conn.commit()
    conn.close()


def main():
    out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join("build", "test_apkg")
    os.makedirs(out_dir, exist_ok=True)

    now = int(time.time())
    db_path = os.path.join(out_dir, "collection.anki2")
    bmp_path = os.path.join(out_dir, BMP_FILENAME)
    apkg_path = os.path.join(out_dir, "EnglishCore.apkg")

    print("Building collection.anki2 ...")
    build_collection(db_path, now)
    print("  deck: %s (%d new, %d learning, %d review)" % (DECK_NAME, NEW_COUNT, LEARNING_COUNT, REVIEW_COUNT))

    print("Writing %s ..." % BMP_FILENAME)
    make_bmp(bmp_path)

    print("Packaging %s ..." % os.path.basename(apkg_path))
    with zipfile.ZipFile(apkg_path, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(db_path, "collection.anki2")
        # Media mapping: numeric id -> filename (Anki `media` entry, no extension).
        with open(os.path.join(out_dir, "media"), "w") as mf:
            json.dump({"1": BMP_FILENAME}, mf)
        z.write(os.path.join(out_dir, "media"), "media")
        z.write(bmp_path, BMP_FILENAME)

    for extra in ("collection.anki2", "media", BMP_FILENAME):
        os.remove(os.path.join(out_dir, extra))

    size = os.path.getsize(apkg_path)
    print()
    print("Done: %s (%d bytes)" % (apkg_path, size))
    print()
    print("Copy EnglishCore.apkg to the SD card at /AnkiEInk/apkg/ (or the SD")
    print("root), then open DeckList -> Import on the device.")


if __name__ == "__main__":
    main()
